# Generated by Django 5.1.6 on 2025-02-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregory',
            new_name='Category',
        ),
    ]
